### ISSUE TITLE
Tutorial corrections

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-tfe-provider-run-triggers#4]
Hi, I'm trying to reproduce this tutorial: https://learn.hashicorp.com/tutorials/terraform/tfe-provider-run-triggers?in=terraform/cloud

but I'm getting this error:

╷
│ Error: Error creating workspace learn-terraform-pipelines-vault-faithful-elf for organization testingBT: invalid attribute
│ 
│ Repository doesn't exist or isn't accessible
│
│   with tfe_workspace.vault,
│   on workspace-vault.tf line 26, in resource "tfe_workspace" "vault":
│   26: resource "tfe_workspace" "vault" {
│

I know that in the tutorial, in update variables, you need to point to the repos, in this case, I'm setting k8s_repo_name

to 

variable "k8s_repo_name" {
  description = "The GH repo where the k8s configuration lives"
  default     = "/vodelerk/learn-terraform-pipelines-k8s"
}

but didn't work,

also, I tried 

variable "k8s_repo_name" {
  description = "The GH repo where the k8s configuration lives"
  default     = "https://www.github.com/vodelerk/learn-terraform-pipelines-k8s"
}

 with no luck,

any advice?

Thanks,

**Comment by vodelerk** [comment]
the right way would be "vodelerk/learn-terraform-pipelines-vault"

it would be really cool to clarify this in the tutorial

**Comment by vodelerk** [comment]
i think in this step:

`sed -i '' 's/test@hashicorp\.com/EMAIL_ADDRESS/g' ./assets/*`

gives an error, the right way would be:

`sed -i 's/test@hashicorp\.com/EMAIL_ADDRESS/g' ./assets/*`

this would be the only one missing, @im2nguyen

**Comment by im2nguyen** [comment]
Can you try without the leading forward slash?

```
variable "k8s_repo_name" {
description = "The GH repo where the k8s configuration lives"
default = "vodelerk/learn-terraform-pipelines-k8s"
}
```

That's how it looks like in the variables.tf file in the repo

**Comment by vodelerk** [comment]
it did the trick, also, it is necessary to add the GCE roles otherwise won't work. Like the other tutorial.

Kubernetes Engine Developer
GKE Hub Service Agent
Owner

![consul000](https://user-images.githubusercontent.com/17457173/119240056-0a820d00-bb13-11eb-8da8-b82644a5d4ff.jpg)
![consul001](https://user-images.githubusercontent.com/17457173/119240057-0ce46700-bb13-11eb-9716-86a1bda0bf56.jpg)
![vault000](https://user-images.githubusercontent.com/17457173/119240062-0fdf5780-bb13-11eb-85d3-ad6118b5cc4a.jpg)

**Comment by vodelerk** [comment]
I did cleaning in the GCE testing environment so I forgot to double-check if I was using the same roles, but it bothers me that I think I was using editor role and not owner, but in this one, for some reason, i had to change it to owner, can you double-check that please? what would be the minimum required permissions in order to this tutorial to work.

**Comment by im2nguyen** [comment]
Yep, in the beginning shows

```
For this tutorial, you will need:

a Google Cloud (GCP) account with access to Compute Admin and GKE Admin
```

**Comment by im2nguyen** [comment]
> i think in this step:
> 
> `sed -i '' 's/test@hashicorp\.com/EMAIL_ADDRESS/g' ./assets/*`
> 
> gives an error, the right way would be:
> 
> `sed -i 's/test@hashicorp\.com/EMAIL_ADDRESS/g' ./assets/*`
> 
> this would be the only one missing, @im2nguyen

Hey @vodelerk, the `sed -i ''` is required to filter out `.` in the `EMAIL_ADDRESS` if they exist. 😄
